# -*- coding: utf-8 -*-
"""Formulas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13kghOWKjvjrWItLjzf-wgZ9XKoAaDGpD
"""

def hello():
    print("Hello")