# -*- coding: utf-8 -*-
"""Teste.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HlgGbFihqNJFL_imwJYghE4NE7mrtGzb
"""

import sys
import os

py_file_location = "/content/drive/My Drive/AI/Testes/"
sys.path.append(os.path.abspath(py_file_location))

import Formulas